# Generated by Django 5.2.3 on 2025-06-25 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afirmacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(default='Anónimo', max_length=100)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('afirmacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='afirmaciones.afirmacion')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(default='Anónimo', max_length=100)),
                ('valor', models.CharField(choices=[('positivo', 'Positivo'), ('neutral', 'Neutral'), ('negativo', 'Negativo')], max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('afirmacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='afirmaciones.afirmacion')),
            ],
        ),
    ]
