# Generated by Django 5.2.3 on 2025-06-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afirmaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='nombre_usuario',
            field=models.CharField(default='Anónimo', max_length=100),
        ),
        migrations.AddField(
            model_name='voto',
            name='nombre_usuario',
            field=models.CharField(default='Anónimo', max_length=100),
        ),
    ]
