# Generated by Django 5.2.3 on 2025-06-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afirmaciones', '0002_remove_comentario_usuario_remove_voto_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='afirmacion',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='afirmacion',
        ),
        migrations.AddField(
            model_name='comentario',
            name='afirmacion_texto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voto',
            name='afirmacion_texto',
            field=models.TextField(default=''),
        ),
    ]
